[www]

user = www-data
group = www-data

listen = 0.0.0.0:9000

pm = dynamic

pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

clear_env = no

; Send access logs to stdout
access.log = /proc/self/fd/1

; Send worker stderr/stdout to container logs
catch_workers_output = yes
decorate_workers_output = no

; Ensure PHP errors go to stderr
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /proc/self/fd/2